name: newbie
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=3.3.9"

dependencies:
  flutter:
    sdk: flutter

  flame: 1.4.0
  flame_audio: ^1.3.2
  flame_tiled: ^1.8.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/tiles/
    - assets/images/newbie/sprite_sheets/
    - assets/images/newbie/sprites/buttons/
    - assets/images/newbie/sprites/
    - assets/images/newbie/map/
    - assets/images/newbie/map/components/
    - assets/images/components/joystick_buttons/

  fonts:
    - family: vt323
      fonts:
        - asset: assets/fonts/vt323/VT323-Regular.ttf
